# This is a workflow for updating the mutation table

name: mutations

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-table:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: SARS-CoV-2_Sequencing

      - name: table update
        run: |
          now=$(date +%Y%m%d_%H%M%S)
          #if new mutations added, then
          #check if format, required variables are correct
          #add mutations to existing latest.tsv
          #copy latest.tsv to ${GITHUB_WORKSPACE}/mutations/archive_tsv/$now.tsv


      - name: make vcf
        run: |
          echo
          #if new mutations, then
          #convert latest.tsv to latest.vcf with some script (add identifier to INFO that can be mapped to changelog)
          #copy latest.vcf to ${GITHUB_WORKSPACE}/mutations/archive_vcf/$now.vcf

      - name: cleanup
        run: |
          echo
          #add new mutation entry to changelog
          #rm new mutation entries

      - name: commit and push new table files
        run: |
          #git add
          #git commit -m "Auto generate new mutation table"
          #git push
